### ISSUE TITLE
Launch Plan

### ISSUE THREAD

**Issue by marcguyer** [bppwrite/bppwrite.github.io#18]
@bppwrite/owners I'm sure you guys are busy with tech and whatnot so this is bad timing...

We're pretty much read to go. Items we're waiting on for launch:

- [x] Hero image for _Row After Row_
- [x] Hero image for _Escape the Room_

There are some things we'd like to touch up after (or before) launch:

- [ ] Retool Ovationtix skins to match the site -- hopefully they have newer, mobile responsive pages. #13
- [ ] Calendar style improvements #14
- [ ] Show/Event page style improvements #15 -- maybe an image gallery? Are there production photos for _Home_ yet?
- [ ] Image gallery/slideshow #12 
- [ ] Content list page styles, pagination #16
- [ ] Individual bios for key staff/crew
- [ ] Add content files for all past shows #17

Anything else you'd like to add?

**Comment by ChadDR** [comment]
My biggest concern at this point is the show/calendar page.  The shows link should, I think, lead me to a “season at a glance” view so that I can see all of my options.  I don’t want to end up at a calendar and have to scroll down a mile before I can see everything playing.  That being said, I also like having a calendar option for the viewer.  And I like the football example you showed me before which would allow someone to scroll through and get what they need.  Currently, I feel like we have a hybrid of both and it’s serving neither purpose.  Does that make sense?  

 

Chad Rabinovitz

Producing Artistic Director

Bloomington Playwrights Project & Adirondack Theatre Festival

 <mailto:ChadDR@aol.com> ChadDR@aol.com

 <http://www.ChadDirects.com> www.ChadDirects.com

**Comment by marcguyer** [comment]
> Currently, I feel like we have a hybrid of both and it’s serving neither purpose.  Does that make sense?

Yes, this is a work in progress. The conversion about the calendar is issue #14.

**Comment by marcguyer** [comment]
This thing is launched
